#１行の文字数。デフォルトの80文字は短すぎるため
# Disabled "Line is too long."
Metrics/LineLength:
  Max: 128

# クラスの説明用のコメントの強制を無効化。
# Disabled "Missing top-level class documentation comment."
Style/Documentation:
  Enabled: false

# Ruby2.3以上だと文字列リテラルが不定になり警告がでてしまうため無効に。
# Disabled "Missing frozen string literal comment."
Style/FrozenStringLiteralComment:
  Enabled: false

# 引用符がダブルクォート以外の場合警告
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Specで警告が出るのを防ぐ
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    